FROM golang:1.24-alpine

RUN go install github.com/air-verse/air@latest

WORKDIR /app

# Copy go.mod and go.sum and download deps
COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY . .

# Run Air
CMD ["air"]