services:
  app:
    build:
      dockerfile: Dockerfile.dev
      context: ./app
    deploy:
      replicas: 1
    ports:
        - "8080:8080"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./:/app
    environment:
      - HOST=localhost:8080
      - ENVIRONMENT=development

