version: '3.8'

services:
  app:
    build: ./app
    deploy:
      replicas: 3
    networks:
      - urls-ac-network
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
        - "80:80"
        - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./etc/letsencrypt/live/urls.ac:/etc/ssl
      - ./frontend/dist:/var/www/urls-ac-frontend
    networks:
      - urls-ac-network
    depends_on:
      - app


  prometheus:
    image: prom/prometheus
    volumes:
        - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - urls-ac-network
    depends_on:
      - app

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - urls-ac-network
    depends_on:
      - prometheus



volumes:
    postgres_data:
    grafana-storage:

networks:
  urls-ac-network:
    driver: bridge