services:
  app:
    build:
      dockerfile: Dockerfile.dev
      context: ./app
    deploy:
      replicas: 1
    ports:
        - "8080:8080"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./app:/app
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - HOST=localhost:8080
      - ENVIRONMENT=development

  postgres:
    ports:
      - "5433:5432"
