services:
  app:
    build:
      dockerfile: Dockerfile.dev
      context: ./app
    deploy:
      replicas: 1
    ports:
        - "8080:8080"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./app:/app
    environment:
      - HOST=localhost:8080
      - ENVIRONMENT=development

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url_shortener
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - urls-ac-network
    ports:
      - "5433:5432"

  redis:
    image: redis:latest

    networks:
      - urls-ac-network
