apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          imagePullPolicy: Always
          image: LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG # update with your actual image
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_CONNECTION_STRING
            - name: REDIS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_CONNECTION_STRING
            - name: HOST
              value: "urls.ac"
            - name: ENVIRONMENT
              value: "production"