root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/app"
bin = "./tmp/main"
include_ext = ["go", "html"]
exclude_dir = ["tmp", "postgres", "migrations", "prometheus"]
exclude_file = []
delay = 1000
stop_on_error = true

[log]
time = true
