/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FiftyfiftyRouteImport } from './routes/fiftyfifty'
import { Route as ApidocsRouteImport } from './routes/apidocs'
import { Route as IndexRouteImport } from './routes/index'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FiftyfiftyRoute = FiftyfiftyRouteImport.update({
  id: '/fiftyfifty',
  path: '/fiftyfifty',
  getParentRoute: () => rootRouteImport,
} as any)
const ApidocsRoute = ApidocsRouteImport.update({
  id: '/apidocs',
  path: '/apidocs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apidocs': typeof ApidocsRoute
  '/fiftyfifty': typeof FiftyfiftyRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apidocs': typeof ApidocsRoute
  '/fiftyfifty': typeof FiftyfiftyRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apidocs': typeof ApidocsRoute
  '/fiftyfifty': typeof FiftyfiftyRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/apidocs' | '/fiftyfifty' | '/login' | '/signup'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/apidocs' | '/fiftyfifty' | '/login' | '/signup'
  id: '__root__' | '/' | '/apidocs' | '/fiftyfifty' | '/login' | '/signup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApidocsRoute: typeof ApidocsRoute
  FiftyfiftyRoute: typeof FiftyfiftyRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fiftyfifty': {
      id: '/fiftyfifty'
      path: '/fiftyfifty'
      fullPath: '/fiftyfifty'
      preLoaderRoute: typeof FiftyfiftyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apidocs': {
      id: '/apidocs'
      path: '/apidocs'
      fullPath: '/apidocs'
      preLoaderRoute: typeof ApidocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApidocsRoute: ApidocsRoute,
  FiftyfiftyRoute: FiftyfiftyRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
